name: JWT Interface

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  working-directory: interfaces/jwt-provider/rust

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: rust-check-action
      uses: wasmcloud/common-actions/rust-check@main
      with:
        working-directory: ${{ env.working-directory }}

  github_release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: rust_check
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.WASMCLOUD_PAT }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  crates_release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${CRATES_TOKEN}
        working-directory: ${{ env.working-directory }}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}